accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path("", views.signup_view, name="signup"),
  path("signup/", views.signup_view, name="signup"),
  path("login/", views.login_view, name ="login"),
  path("logout/", views.logout_view, name = "logout"),
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'


urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_details, name = "detail"),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('accounts/', include('accounts.urls')),
    path('', article_views.article_list, name = "home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
  title = models.CharField(max_length=100)
  
  slug = models.SlugField()

  body = models.TextField()
  
  date = models.DateTimeField(auto_now_add=True)
  thumb = models.ImageField(default='default.png', blank=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


# add in thumbnail and author later

# python3 manage.py makemigrations
# python3 manage.py migrate

  def __str__(self):
    return self.title
  def snippet(self):
    return self.body[:50]

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
  class Meta:
    model = models.Article
    fields = ['title','body','slug','thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      # log the user in
      login(request, user)
      return redirect('articles:list')
  else:
    form = UserCreationForm()
  return render(request, 'accounts/signup.html', {'form':form})


def login_view(request):
  if request.method == 'POST':
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
      #log in the user
      user = form.get_user()
      login(request, user)
      if 'next' in request.POST:
        return redirect(request.POST.get('next'))
      else:
        return redirect('articles:list')
  else:
    form = AuthenticationForm()
  return render(request,"accounts/login.html", {'form':form})

""" def logout_view(request):
  if request.method == 'POST':
    logout(request)
    return redirect('articles:list') """

def logout_view(request):
  if request.method == 'POST':
    logout(request)
    return redirect('articles:list')

articles/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
  articles = Article.objects.all().order_by('date',)
  return render(request, 'articles/article_list.html', {'articles':articles})

def article_details(request, slug):
  #return HttpResponse(slug)
  article = Article.objects.get(slug=slug)
  return render(request, "articles/article_detail.html", {'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
  if request.method == 'POST':
    form = forms.CreateArticle(request.POST, request.FILES)
    if form.is_valid():
      #Save article to database
      instance = form.save(commit=False)
      instance.author = request.user
      instance.save()
      return redirect('articles:list')
  else:
    form = forms.CreateArticle()
  return render(request, 'articles/article_create.html', {'form':form})
  

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
  # return HttpResponse('homepage')
  return render(request, "homepage.html")


def about(request):
  # return HttpResponse('about')
  return render(request,"about.html")

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" class="site-form" method="post">
  {% csrf_token %} {{form}} {% if request.GET.next %}
  <input type="hidden" name="text" value="{{request.GET.next}}" />
  {% endif %}
  <input type="submit" value="Login" />
</form>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Logout</h1>
<p>You have been logged out. Stand by to be redirected to the home page.</p>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Signup</h1>
<form action="/accounts/signup/" class="site-form" method="post">
  {% csrf_token %} 
  {{form}}
  <input type="submit" value="Signup" />
</form>

{% endblock %}

articles/templates/about.html
{% extends 'base_layout.html' %} {% block content %}

<body>
  <h1 style="margin-left: 50%";>About us</h1>
  <p>This website was made entirely in Django framework in about 3 days using the guides from <a href=https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1" style="color: blue;text-decoration: underline;">The Net Ninja's Django Tutorial</a>. Check him out if you have the time!</p>
</body>


{%endblock%}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %} {% block content %}

<div class="create-article">
  <h2>Create an awesome new article</h2>
  <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
  </form>
<div>

{%endblock%}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %} {% block content %}

<div class="article-detail">
  <div class="article">
    <img src="{{article.thumb.url}}"  width=200px, height=200px>
    <h2>{{article.title}}</h2>
    <p style="
    margin-top: 0px;
">By {{article.author}}.</p>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>

{%endblock%}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}


{% block content %}
<h1>Article List</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article" style="background-color: #444444;border-radius: 45px;">
    <h2 style="margin-left:45px; padding-top: 10px"><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
    <p style="margin-top: 0px;margin-left:45px" >By: {{article.author}}. {{article.date}}</p>
    <p style="margin-left:45px;margin-bottom: 20px; padding-bottom: 20px">{{article.snippet}}...</p>
    
  </div>
  {% endfor %}
</div>
{% endblock %}

articles/templates/articles/logout.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Logout</h1>
<p>You have been logged out. Stand by to be redirected to the home page.</p>

{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.png" />
  </head>

  <nav id="website-header" style="
  background-color: rgba(91, 254, 232, 0.29);
  border: 2px solid rgba(114, 106, 255, 0.53);
  padding-top: 12px;
  padding-bottom: 12px;
  justify-items: right;"
>
    <a href="{% url 'articles:list' %}" class="nav-links">
      <img src="{% static 'logo.png'%}" id="site-logo" />
    </a>

    <a href="/about/" class="nav-links" style="float:right;margin-top: 20px;margin-bottom: 20px;">About us.</a>
      
    {% if user.is_authenticated %}

      <form
        action="{% url 'accounts:logout' %}"
        class="logout-link"
        method="post"
        style="display:inline"
      >
        {% csrf_token %}
        <button type="submit" class="nav-links" style="
        background: none;
        border: none;
        color: white;
        float: right;
        margin-top: 20px;
        margin-bottom: 20px;
        cursor:pointer;
    ">Logout</button>
      </form>

      <a href="{% url 'articles:create' %}" class="nav-links" style="float:right;margin-top: 20px;margin-bottom: 20px;">Create a new article.</a>
      <div>Logged in as {{user}}</div>
      
      {% else %}

      <a href="{% url 'accounts:login' %}" class="nav-links">Login</a>

      {% endif %}
  </nav>

  <body>

    <div class="wrapper" style="margin-left:50px; margin-right: 50px;">
      <h1></h1>
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Homepage</title>
  </head>
  <body>
    <h1>Welcome to djangonautic.</h1>
  </body>
</html>

templates/templates/about.html
{% extends 'base_layout.html' %} {% block content %}

<body>
  <h1 style="margin-left: 50%";>About us</h1>
  <p>This website was made entirely in Django framework in about 3 days using the guides from <a href=https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1" style="color: blue;text-decoration: underline;">The Net Ninja's Django Tutorial</a>. Check him out if you have the time!</p>
</body>


{%endblock%}